### ISSUE TITLE
Fail to install on MacOS

### ISSUE THREAD

**Issue by simpl1g** [red-data-tools/red-arrow-duckdb#1]
```shell
gem install red-arrow-duckdb
```
Fails with 
```
/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:389:in `parse_pc': .pc doesn't exist: <openssl> (PackageConfig::NotFoundError)
```

MacOS 11.4 (20F71)
Ruby 2.7.4

<details>
  <summary>gem_make.out</summary>

```
current directory: /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/red-arrow-duckdb-1.0.0/ext/arrow-duckdb
/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/bin/ruby -I /Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0 -r ./siteconf20211105-75237-qqmjre.rb extconf.rb
checking --enable-debug-build option... no
checking C++ compiler... g++
checking g++ version... 12 (gnu++14)
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Waggregate-return option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... yes
checking for -Wunsafe-loop-optimizations option to compiler... no
checking for -Wwrite-strings option to compiler... yes
checking for Homebrew... yes
checking for arrow-glib... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/bin/$(RUBY_BASE_NAME)
	--enable-debug-build
	--disable-debug-build
	--enable-debug-build
	--disable-debug-build
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:389:in `parse_pc': .pc doesn't exist: <openssl> (PackageConfig::NotFoundError)
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:233:in `declaration'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:178:in `requires_private'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:509:in `block in all_required_packages'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:259:in `collect_requires'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:265:in `block in collect_requires'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `each'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `collect_requires'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:265:in `block in collect_requires'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `each'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `collect_requires'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:265:in `block in collect_requires'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `each'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `collect_requires'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:265:in `block in collect_requires'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `each'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `collect_requires'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:508:in `all_required_packages'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:283:in `collect_cflags'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:191:in `cflags_only_other'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:569:in `cflags_only_other'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/pkg-config-1.4.6/lib/pkg-config.rb:616:in `have_package'
	from /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/glib2-3.4.9/lib/mkmf-gnome.rb:458:in `required_pkg_config_package'
	from extconf.rb:18:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/k.ilcenko/.rvm/gems/ruby-2.7.4/extensions/x86_64-darwin-20/2.7.0/red-arrow-duckdb-1.0.0/mkmf.log

extconf failed, exit code 1
```

</details>

<details>
  <summary>mkmf.log</summary>

```
check_debug_build: checking --enable-debug-build option... -------------------- no

--------------------

check_cxx: checking C++ compiler... -------------------- g++

--------------------

check_version: checking g++ version... -------------------- 12 (gnu++14)

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
--------------------

"g++ -Werror -Wdeprecated-register -c conftest.cpp"
checked program was:
/* begin */
1: int main(void) {return 0;}/* end */

checking for --enable-debug-build option... -------------------- no

--------------------

try_compiler_option: checking for -Wall option to compiler... -------------------- yes

"gcc -o conftest -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe conftest.c  -L. -L/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/lib -L. -fstack-protector-strong -L/usr/local/lib     -lruby.2.7   "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe  -Wall -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Waggregate-return option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall  -Waggregate-return -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wcast-align option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return  -Wcast-align -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wextra option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align  -Wextra -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wformat=2 option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra  -Wformat=2 -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Winit-self option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2  -Winit-self -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wlarger-than-65500 option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self  -Wlarger-than-65500 -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wmissing-declarations option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500  -Wmissing-declarations -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wmissing-format-attribute option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations  -Wmissing-format-attribute -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wmissing-include-dirs option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute  -Wmissing-include-dirs -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wmissing-noreturn option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs  -Wmissing-noreturn -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wmissing-prototypes option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn  -Wmissing-prototypes -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wnested-externs option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes  -Wnested-externs -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wold-style-definition option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs  -Wold-style-definition -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wpacked option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition  -Wpacked -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked  -Wp,-D_FORTIFY_SOURCE=2 -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wpointer-arith option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wp,-D_FORTIFY_SOURCE=2  -Wpointer-arith -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wundef option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith  -Wundef -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wout-of-line-declaration option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wundef  -Wout-of-line-declaration -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wunsafe-loop-optimizations option to compiler... -------------------- no

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wundef -Wout-of-line-declaration  -Wunsafe-loop-optimizations -Werror -c conftest.c"
error: unknown warning option '-Wunsafe-loop-optimizations' [-Werror,-Wunknown-warning-option]
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

try_compiler_option: checking for -Wwrite-strings option to compiler... -------------------- yes

"gcc -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-darwin20 -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/Users/k.ilcenko/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I. -I/Users/k.ilcenko/.rvm/gems/ruby-2.7.4/gems/extpp-0.1.0/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wundef -Wout-of-line-declaration  -Wwrite-strings -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
/* end */

--------------------

setup_homebrew: checking for Homebrew... -------------------- yes

--------------------

have_package: checking for arrow-glib... -------------------- yes

--------------------


```

</details>

```
ruby -rpp -r pkg-config -e 'pp PackageConfig.new("openssl")' 
#<PackageConfig:0x00007fa57b8674a0
 @declarations=nil,
 @msvc_syntax=nil,
 @name="openssl",
 @options={},
 @override_variables={},
 @path_position=nil,
 @paths=
  ["/usr/local/lib/pkgconfig",
   "/usr/local/share/pkgconfig",
   "/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11",
   "/usr/local/lib/pkgconfig",
   "/usr/local/share/pkgconfig",
   "/usr/lib/pkgconfig",
   "/opt/X11/lib/pkgconfig"],
 @pc_path=nil,
 @variables=nil>
```

Also tried to install with custom cflag, it fixed `error: unknown warning option '-Wunsafe-loop-optimizations' [-Werror,-Wunknown-warning-option]`, but build still fails
```
gem install red-arrow-duckdb -- --with-cflags="-Wno-error=unknown-warning-option" 
```

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.
