### ISSUE TITLE
Docker's install problem

### ISSUE THREAD

**Issue by augustocbx** [red-data-tools/red-arrow-duckdb#3]
I'm trying to install the gem inside a docker container.

Dockerfile
```
FROM ruby:2.7.2-buster

ENV DEBIAN_FRONTEND noninteractive
ENV BUILD_DEPS=' \
                 git \
                 build-essential \
                 cmake \
                 autoconf \
                 automake \
                 libxml2-dev \
                 libxslt-dev \
                 nodejs \
                 yarn \
               '

RUN apt-get update
RUN apt-get install -y --no-install-recommends -V lsb-release wget

RUN wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
RUN apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb

RUN apt-get update && apt-get install -y --no-install-recommends \
        tzdata \
        locales \
        imagemagick \
        xvfb xauth xorg cutycapt \
        file \
        zip \
        libqt5core5a \
        hunspell \
        libpq-dev \
        libgandiva-dev \
        libpcre3-dev \
        locales-all \
        libfontconfig \
        libfreetype6 \
        libgirepository1.0-dev \
        fonts-noto \
        fonts-liberation \
        fonts-ipafont-gothic \
        fonts-wqy-zenhei \
        fonts-tlwg-loma-otf \
        xfonts-cyrillic \
        xfonts-scalable \
        shared-mime-info \
        gtk-doc-tools \
        postgresql-client-11 \
        gnupg apt-transport-https \
        $BUILD_DEPS


RUN echo 'deb http://deb.debian.org/debian testing main' >> /etc/apt/sources.list
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y g++ \
        gcc \
        libglib2.0-dev \
        libmount-dev \
        libselinux1-dev \
        libgirepository1.0-dev \
        libarrow-glib-dev \
        libarrow-dataset-dev \
        libparquet-dev \
        libparquet-glib-dev \
        libarrow-dataset-glib-dev \
        libarrow-dev \
        meson \
        ninja-build libc6-dev-i386 gcc-multilib g++-multilib lib32readline6-dev \
        python3 \
        python3-pip \
        python3-dev

RUN pip3 install --upgrade setuptools numpy

RUN wget https://github.com/duckdb/duckdb/releases/download/v0.3.2/libduckdb-linux-amd64.zip
RUN unzip libduckdb-linux-amd64.zip
RUN cp duckdb.* /usr/local/include/
RUN cp libduckdb.so /usr/local/lib/
RUN ldconfig /usr/local/lib

WORKDIR /app

# required by CLD native extension
ENV CFLAGS="-Wno-narrowing"
ENV CXXFLAGS="$CFLAGS"

RUN gem install bundler --version \
    "$(grep -A1 'BUNDLED WITH' Gemfile.lock | tail -n1 | tr -d ' ')"

RUN bundle config without development test

RUN apt-get autoremove -y
RUN apt-get install -f

COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN bundle install --deployment --frozen --no-prune

RUN rm -rf /var/lib/apt/lists/* \
    && rm -rf tmp/cache \
    && apt-get remove $BUILD_DEPS --purge -y --auto-remove \
    && rm -rf /var/cache/apt/archives/*

```

Gemfile
```
source 'https://rubygems.org'
gem 'rake'
gem 'duckdb'
gem 'red-arrow'
gem 'red-arrow-dataset'
gem 'red-arrow-duckdb'
gem 'red-parquet'
```

Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    bigdecimal (3.0.2)
    duckdb (0.3.2.0)
    extpp (0.1.0)
    gio2 (3.4.9)
      gobject-introspection (= 3.4.9)
    glib2 (3.4.9)
      native-package-installer (>= 1.0.3)
      pkg-config (>= 1.3.5)
    gobject-introspection (3.4.9)
      glib2 (= 3.4.9)
    native-package-installer (1.1.1)
    pkg-config (1.4.6)
    rake (13.0.6)
    red-arrow (6.0.1)
      bigdecimal (>= 2.0.3)
      extpp (>= 0.0.7)
      gio2 (>= 3.4.9)
      native-package-installer
      pkg-config
    red-arrow-dataset (6.0.1)
      red-arrow (= 6.0.1)
    red-arrow-duckdb (1.0.2)
      duckdb
      red-arrow
    red-parquet (6.0.1)
      red-arrow (= 6.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  duckdb
  rake
  red-arrow
  red-arrow-dataset
  red-arrow-duckdb
  red-parquet

BUNDLED WITH
   2.2.19
```

The output:
```
#28 [24/25] RUN bundle install --deployment --frozen --no-prune
#28 sha256:b66940219908731461c29040f033fa76499fa78bf54ea12a20b3e01a8a4df2e6
#28 0.303 [DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local deployment 'true'`, and stop using this flag
#28 0.303 [DEPRECATED] The `--frozen` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local frozen 'true'`, and stop using this flag
#28 0.303 [DEPRECATED] The `--no-prune` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local no_prune 'true'`, and stop using this flag
#28 1.445 Fetching gem metadata from https://rubygems.org/....
#28 1.766 Fetching rake 13.0.6
#28 1.975 Installing rake 13.0.6
#28 2.013 Using bundler 2.3.9
#28 2.014 Fetching native-package-installer 1.1.1
#28 2.014 Fetching pkg-config 1.4.6
#28 2.014 Fetching bigdecimal 3.0.2
#28 2.014 Fetching duckdb 0.3.2.0
#28 2.014 Fetching extpp 0.1.0
#28 2.152 Installing duckdb 0.3.2.0 with native extensions
#28 2.156 Installing extpp 0.1.0
#28 2.159 Installing pkg-config 1.4.6
#28 2.169 Installing native-package-installer 1.1.1
#28 2.218 Installing bigdecimal 3.0.2 with native extensions
#28 2.349 Fetching glib2 3.4.9
#28 2.548 Installing glib2 3.4.9 with native extensions
#28 25.46 Fetching gobject-introspection 3.4.9
#28 25.63 Installing gobject-introspection 3.4.9 with native extensions
#28 33.74 Fetching gio2 3.4.9
#28 33.87 Installing gio2 3.4.9 with native extensions
#28 36.01 Fetching red-arrow 6.0.1
#28 36.18 Installing red-arrow 6.0.1 with native extensions
#28 53.13 Fetching red-arrow-duckdb 1.0.2
#28 53.13 Fetching red-arrow-dataset 6.0.1
#28 53.13 Fetching red-parquet 6.0.1
#28 53.32 Installing red-parquet 6.0.1 with native extensions
#28 53.33 Installing red-arrow-duckdb 1.0.2 with native extensions
#28 53.34 Installing red-arrow-dataset 6.0.1 with native extensions
#28 59.56 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#28 59.56
#28 59.56 current directory:
#28 59.56 /app/vendor/bundle/ruby/2.7.0/gems/red-arrow-duckdb-1.0.2/ext/arrow-duckdb
#28 59.56 /usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
#28 59.56 ./siteconf20220310-8-26n7rj.rb extconf.rb
#28 59.56 checking --enable-debug-build option... no
#28 59.56 checking C++ compiler... g++
#28 59.56 checking g++ version... 11.2 (gnu++14)
#28 59.56 checking for --enable-debug-build option... no
#28 59.56 checking for -Wall option to compiler... yes
#28 59.56 checking for -Waggregate-return option to compiler... yes
#28 59.56 checking for -Wcast-align option to compiler... yes
#28 59.56 checking for -Wextra option to compiler... yes
#28 59.56 checking for -Wformat=2 option to compiler... yes
#28 59.56 checking for -Winit-self option to compiler... yes
#28 59.56 checking for -Wlarger-than-65500 option to compiler... yes
#28 59.56 checking for -Wmissing-declarations option to compiler... yes
#28 59.56 checking for -Wmissing-format-attribute option to compiler... yes
#28 59.56 checking for -Wmissing-include-dirs option to compiler... yes
#28 59.56 checking for -Wmissing-noreturn option to compiler... yes
#28 59.56 checking for -Wmissing-prototypes option to compiler... yes
#28 59.56 checking for -Wnested-externs option to compiler... no
#28 59.56 checking for -Wold-style-definition option to compiler... yes
#28 59.56 checking for -Wpacked option to compiler... yes
#28 59.56 checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
#28 59.56 checking for -Wpointer-arith option to compiler... yes
#28 59.56 checking for -Wundef option to compiler... yes
#28 59.56 checking for -Wout-of-line-declaration option to compiler... no
#28 59.56 checking for -Wunsafe-loop-optimizations option to compiler... yes
#28 59.56 checking for -Wwrite-strings option to compiler... yes
#28 59.56 checking for Homebrew... no
#28 59.56 checking for Homebrew... no
#28 59.56 checking for arrow-glib... yes
#28 59.56 checking for arrow-dataset... yes
#28 59.56 checking for -lduckdb... yes
#28 59.56 creating Makefile
#28 59.56
#28 59.56 current directory:
#28 59.56 /app/vendor/bundle/ruby/2.7.0/gems/red-arrow-duckdb-1.0.2/ext/arrow-duckdb
#28 59.56 make "DESTDIR=" clean
#28 59.56
#28 59.56 current directory:
#28 59.56 /app/vendor/bundle/ruby/2.7.0/gems/red-arrow-duckdb-1.0.2/ext/arrow-duckdb
#28 59.56 make "DESTDIR="
#28 59.56 compiling arrow-duckdb-registration.cpp
#28 59.56 arrow-duckdb-registration.cpp:105:26: error: ‘TableFilter’ is not a member of
#28 59.56 ‘duckdb’; did you mean ‘TableFilterSet’?
#28 59.56   105 |   convert_filter(duckdb::TableFilter *filter,
#28 59.56       |                          ^~~~~~~~~~~
#28 59.56       |                          TableFilterSet
#28 59.56 arrow-duckdb-registration.cpp:105:39: error: ‘filter’ was not declared in this
#28 59.56 scope
#28 59.56   105 |   convert_filter(duckdb::TableFilter *filter,
#28 59.56       |                                       ^~~~~~
#28 59.56 arrow-duckdb-registration.cpp:106:30: error: expected primary-expression before
#28 59.56 ‘&’ token
#28 59.56   106 |                  std::string &column_name)
#28 59.56       |                              ^
#28 59.56 arrow-duckdb-registration.cpp:106:31: error: ‘column_name’ was not declared in
#28 59.56 this scope
#28 59.56   106 |                  std::string &column_name)
#28 59.56       |                               ^~~~~~~~~~~
#28 59.56 arrow-duckdb-registration.cpp:107:3: error: expected ‘,’ or ‘;’ before ‘{’ token
#28 59.56   107 |   {
#28 59.56       |   ^
#28 59.56 arrow-duckdb-registration.cpp:167:45: error: ‘TableFilter’ is not a member of
#28 59.56 ‘duckdb’; did you mean ‘TableFilterSet’?
#28 59.56   167 |                     std::unique_ptr<duckdb::TableFilter>
#28 59.56       |                                             ^~~~~~~~~~~
#28 59.56       |                                             TableFilterSet
#28 59.56 arrow-duckdb-registration.cpp:167:45: error: ‘TableFilter’ is not a member of
#28 59.56 ‘duckdb’; did you mean ‘TableFilterSet’?
#28 59.56   167 |                     std::unique_ptr<duckdb::TableFilter>
#28 59.56       |                                             ^~~~~~~~~~~
#28 59.56       |                                             TableFilterSet
#28 59.56 arrow-duckdb-registration.cpp:167:56: error: template argument 1 is invalid
#28 59.56   167 |                     std::unique_ptr<duckdb::TableFilter>
#28 59.56       |                                                        ^
#28 59.56 arrow-duckdb-registration.cpp:167:56: error: template argument 2 is invalid
#28 59.56 arrow-duckdb-registration.cpp:168:19: error: template argument 2 is invalid
#28 59.56   168 |                   > &filters,
#28 59.56       |                   ^
#28 59.56 arrow-duckdb-registration.cpp:168:19: error: template argument 5 is invalid
#28 59.56 arrow-duckdb-registration.cpp: In function ‘arrow::compute::Expression
#28 59.56 {anonymous}::convert_filters(int&, std::unordered_map<long unsigned int,
#28 59.56 std::__cxx11::basic_string<char> >&)’:
#28 59.56 arrow-duckdb-registration.cpp:172:28: error: request for member ‘begin’ in
#28 59.56 ‘filters’, which is of non-class type ‘int’
#28 59.56   172 |     for (auto it = filters.begin(); it != filters.end(); ++it) {
#28 59.56       |                            ^~~~~
#28 59.56 arrow-duckdb-registration.cpp:172:51: error: request for member ‘end’ in
#28 59.56 ‘filters’, which is of non-class type ‘int’
#28 59.56   172 |     for (auto it = filters.begin(); it != filters.end(); ++it) {
#28 59.56       |                                                   ^~~
#28 59.56 arrow-duckdb-registration.cpp: In function
#28 59.56 ‘arrow::Result<std::unique_ptr<duckdb::ArrowArrayStreamWrapper> >
#28 59.56 {anonymous}::arrow_table_produce_internal(uintptr_t,
#28 59.56 std::pair<std::unordered_map<long unsigned int, std::__cxx11::basic_string<char>
#28 59.56 >, std::vector<std::__cxx11::basic_string<char> > >&,
#28 59.56 duckdb::TableFilterCollection*)’:
#28 59.56 arrow-duckdb-registration.cpp:195:30: error: invalid use of incomplete type
#28 59.56 ‘class duckdb::TableFilterSet’
#28 59.56   195 |       !filters->table_filters->filters.empty();
#28 59.56       |                              ^~
#28 59.56 In file included from arrow-duckdb-registration.cpp:24:
#28 59.56 /usr/local/include/duckdb.hpp:10044:7: note: forward declaration of ‘class
#28 59.56 duckdb::TableFilterSet’
#28 59.56 10044 | class TableFilterSet;
#28 59.56       |       ^~~~~~~~~~~~~~
#28 59.56 In file included from /usr/include/arrow/buffer.h:28,
#28 59.56                  from /usr/include/arrow/array/data.h:26,
#28 59.56                  from /usr/include/arrow/array/array_base.h:26,
#28 59.56                  from /usr/include/arrow/array.h:37,
#28 59.56                  from /usr/include/arrow/api.h:22,
#28 59.56                  from /usr/include/arrow-glib/basic-array.hpp:22,
#28 59.56                  from /usr/include/arrow-glib/array.hpp:22,
#28 59.56                  from /usr/include/arrow-glib/arrow-glib.hpp:24,
#28 59.56                  from arrow-duckdb-registration.cpp:17:
#28 59.56 arrow-duckdb-registration.cpp:198:71: error: invalid use of incomplete type
#28 59.56 ‘class duckdb::TableFilterSet’
#28 59.56 198 |
#28 59.56 scanner_builder->Filter(convert_filters(filters->table_filters->filters,
#28 59.56       |                                                                       ^~
#28 59.56 In file included from arrow-duckdb-registration.cpp:24:
#28 59.56 /usr/local/include/duckdb.hpp:10044:7: note: forward declaration of ‘class
#28 59.56 duckdb::TableFilterSet’
#28 59.56 10044 | class TableFilterSet;
#28 59.56       |       ^~~~~~~~~~~~~~
#28 59.56 make: *** [Makefile:237: arrow-duckdb-registration.o] Error 1
#28 59.56
#28 59.56 make failed, exit code 2
#28 59.56
#28 59.56 Gem files will remain installed in
#28 59.56 /app/vendor/bundle/ruby/2.7.0/gems/red-arrow-duckdb-1.0.2 for inspection.
#28 59.56 Results logged to
#28 59.56 /app/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/red-arrow-duckdb-1.0.2/gem_make.out
#28 59.56
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in `run'
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:51:in `block in make'
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in `each'
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in `make'
#28 59.56 /usr/local/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:63:in `block in
#28 59.56 build'
#28 59.56   /usr/local/lib/ruby/2.7.0/tempfile.rb:291:in `open'
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
#28 59.56 /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in `block in
#28 59.56 build_extension'
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `synchronize'
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `build_extension'
#28 59.56 /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in `block in
#28 59.56 build_extensions'
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `each'
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `build_extensions'
#28 59.56   /usr/local/lib/ruby/2.7.0/rubygems/installer.rb:844:in `build_extensions'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/rubygems_gem_installer.rb:71:in
#28 59.56 `build_extensions'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/rubygems_gem_installer.rb:28:in
#28 59.56 `install'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/source/rubygems.rb:204:in
#28 59.56 `install'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/gem_installer.rb:54:in
#28 59.56 `install'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/gem_installer.rb:16:in
#28 59.56 `install_from_spec'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:186:in
#28 59.56 `do_install'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:177:in
#28 59.56 `block in worker_pool'
#28 59.56   /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:62:in `apply_func'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:57:in `block in
#28 59.56 process_queue'
#28 59.56   /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:54:in `loop'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:54:in
#28 59.56 `process_queue'
#28 59.56 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:91:in `block (2
#28 59.56 levels) in create_threads'
#28 59.56
#28 59.56 An error occurred while installing red-arrow-duckdb (1.0.2), and Bundler cannot
#28 59.56 continue.
#28 59.56
#28 59.56 In Gemfile:
#28 59.56   red-arrow-duckdb
#28 ERROR: executor failed running [/bin/sh -c bundle install --deployment --frozen --no-prune]: exit code: 5
------
 > [24/25] RUN bundle install --deployment --frozen --no-prune:
------
executor failed running [/bin/sh -c bundle install --deployment --frozen --no-prune]: exit code: 5
```

**Comment by augustocbx** [comment]
@kou, do you have a sample of Dockerfile which I could use by the base to adapt mine?

**Comment by kou** [comment]
This is a DuckDB's problem. Building DuckDB with `-DAMALGAMATION_BUILD=ON` misses `TableFilterSet` class. Could you report this to https://github.com/duckdb/duckdb/issues like https://github.com/duckdb/duckdb/pull/2137 ? It seems that `src/include/table_filter.hpp` is missing.

**Comment by augustocbx** [comment]
Update: I had success installing it on Docker, compiling the duckdb by myself.

**Comment by kou** [comment]
Anyway, could you report this problem to DuckDB for future users?

**Comment by augustocbx** [comment]
Yes, It's there:
https://github.com/duckdb/duckdb/issues/3236

**Comment by kou** [comment]
Thanks.
I close this.
